
"""
AgisRecon - Base Module

Defines the common interface for all reconnaissance tool modules.

Every tool wrapper should inherit from BaseModule and implement
the required methods.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional


class BaseModule(ABC):
    """
    Base class for all AgisRecon reconnaissance modules.

    Each module represents a wrapper around an external reconnaissance
    tool such as Subfinder, Assetfinder, DNSX, HTTPX, Nmap, Katana,
    or Nuclei.
    """

    name: str = "base"
    description: str = "Base reconnaissance module"
    command: Optional[str] = None

    def __init__(self, config: Optional[Dict[str, Any]] = None) -> None:
        """
        Initialize the module.

        Args:
            config: Optional configuration dictionary for the module.
        """
        self.config = config or {}
        self.results: List[Any] = []

    @abstractmethod
    def run(self, target: str, **kwargs: Any) -> List[Any]:
        """
        Execute the module against the target.

        Args:
            target: Target domain, IP address, URL, or other supported input.
            **kwargs: Additional module-specific options.

        Returns:
            A list containing the module results.
        """
        raise NotImplementedError

    def validate_target(self, target: str) -> bool:
        """
        Perform basic target validation.

        This provides a simple common validation layer. Individual
        modules can override it when they require more specific
        validation.

        Args:
            target: Target supplied to the module.

        Returns:
            True if the target is usable, otherwise False.
        """
        if not isinstance(target, str):
            return False

        target = target.strip()

        if not target:
            return False

        return True

    def clear_results(self) -> None:
        """
        Clear results from the previous execution.
        """
        self.results.clear()

    def add_result(self, result: Any) -> None:
        """
        Add a result to the module result collection.

        Args:
            result: Result produced by the module.
        """
        if result is not None:
            self.results.append(result)

    def get_results(self) -> List[Any]:
        """
        Return the results generated by the module.

        Returns:
            List of collected results.
        """
        return self.results

    def is_available(self) -> bool:
        """
        Check whether the external tool required by the module
        is available.

        The default implementation returns True.

        Individual tool wrappers should override this method to
        perform an actual executable check.
        """
        return True

    def get_info(self) -> Dict[str, Any]:
        """
        Return basic information about the module.

        Returns:
            Dictionary containing module metadata.
        """
        return {
            "name": self.name,
            "description": self.description,
            "command": self.command,
        }

    def __repr__(self) -> str:
        """
        Return a readable representation of the module.
        """
        return f"<{self.__class__.__name__} name='{self.name}'>"

