"""
AgisRecon2 - Markdown Output

Handles formatting and saving reconnaissance results
in Markdown format.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional, Union


class MarkdownOutput:
    """Handle AgisRecon2 Markdown output."""

    def __init__(
        self,
        output_dir: Optional[Union[str, Path]] = None,
    ):
        """
        Initialize Markdown output handler.

        Args:
            output_dir: Directory where Markdown reports
                        will be stored.
        """

        if output_dir is None:
            output_dir = Path("output") / "markdown"

        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

    # ---------------------------------------------------------
    # Format results
    # ---------------------------------------------------------

    def format_results(
        self,
        results: Any,
        target: Optional[str] = None,
        module: Optional[str] = None,
        title: str = "AgisRecon2 Reconnaissance Report",
    ) -> str:
        """
        Convert reconnaissance results into Markdown.
        """

        timestamp = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        lines = [
            f"# {title}",
            "",
            "## Scan Information",
            "",
            "| Field | Value |",
            "|---|---|",
            f"| Tool | AgisRecon2 |",
            f"| Target | {target or 'N/A'} |",
            f"| Module | {module or 'N/A'} |",
            f"| Timestamp | {timestamp} |",
            "",
            "## Results",
            "",
        ]

        lines.extend(
            self._format_value(results)
        )

        lines.extend(
            [
                "",
                "---",
                "",
                "*Generated by AgisRecon2*",
            ]
        )

        return "\n".join(lines)

    # ---------------------------------------------------------
    # Format values
    # ---------------------------------------------------------

    def _format_value(
        self,
        value: Any,
        level: int = 0,
    ) -> list[str]:
        """Format different Python data types as Markdown."""

        lines: list[str] = []

        if isinstance(value, dict):

            for key, item in value.items():

                heading_level = min(level + 3, 6)

                lines.append(
                    f"{'#' * heading_level} "
                    f"{self._safe_text(key)}"
                )
                lines.append("")

                lines.extend(
                    self._format_value(
                        item,
                        level + 1,
                    )
                )

                lines.append("")

        elif isinstance(value, (list, tuple, set)):

            if not value:
                lines.append("_No results found._")
                return lines

            for item in value:

                if isinstance(
                    item,
                    (dict, list, tuple, set),
                ):
                    lines.append(
                        self._format_inline(item)
                    )
                else:
                    lines.append(
                        f"- {self._safe_text(item)}"
                    )

        else:

            lines.append(
                self._safe_text(value)
            )

        return lines

    # ---------------------------------------------------------
    # Inline formatting
    # ---------------------------------------------------------

    def _format_inline(
        self,
        value: Any,
    ) -> str:
        """Convert a value into a readable Markdown line."""

        if isinstance(value, dict):

            parts = []

            for key, item in value.items():
                parts.append(
                    f"**{self._safe_text(key)}:** "
                    f"{self._safe_text(item)}"
                )

            return "- " + " | ".join(parts)

        if isinstance(
            value,
            (list, tuple, set),
        ):
            return "- " + ", ".join(
                self._safe_text(item)
                for item in value
            )

        return f"- {self._safe_text(value)}"

    # ---------------------------------------------------------
    # Save
    # ---------------------------------------------------------

    def save(
        self,
        results: Any,
        filename: Optional[str] = None,
        target: Optional[str] = None,
        module: Optional[str] = None,
        title: str = "AgisRecon2 Reconnaissance Report",
    ) -> Path:
        """
        Save reconnaissance results as a Markdown file.

        Returns:
            Path to the generated Markdown file.
        """

        content = self.format_results(
            results=results,
            target=target,
            module=module,
            title=title,
        )

        if filename is None:
            filename = self._generate_filename(
                target=target,
                module=module,
            )

        if not filename.endswith(".md"):
            filename += ".md"

        file_path = self.output_dir / filename

        file_path.write_text(
            content,
            encoding="utf-8",
        )

        return file_path

    # ---------------------------------------------------------
    # Filename generation
    # ---------------------------------------------------------

    @staticmethod
    def _generate_filename(
        target: Optional[str] = None,
        module: Optional[str] = None,
    ) -> str:
        """Generate a timestamp-based Markdown filename."""

        timestamp = datetime.now().strftime(
            "%Y%m%d_%H%M%S"
        )

        target_name = (
            str(target)
            .replace("://", "_")
            .replace("/", "_")
            .replace("\\", "_")
            .replace(":", "_")
            if target
            else "target"
        )

        module_name = (
            str(module)
            .replace(" ", "_")
            if module
            else "scan"
        )

        return (
            f"{target_name}_"
            f"{module_name}_"
            f"{timestamp}.md"
        )

    # ---------------------------------------------------------
    # Utility
    # ---------------------------------------------------------

    @staticmethod
    def _safe_text(
        value: Any,
    ) -> str:
        """Convert a value safely to Markdown text."""

        text = str(value)

        # Prevent accidental Markdown table corruption.
        text = text.replace("|", "\\|")

        return text


# -------------------------------------------------------------
# Default Markdown output instance
# -------------------------------------------------------------

markdown_output = MarkdownOutput()


# -------------------------------------------------------------
# Convenience functions
# -------------------------------------------------------------

def save_markdown(
    results: Any,
    filename: Optional[str] = None,
    target: Optional[str] = None,
    module: Optional[str] = None,
    title: str = "AgisRecon2 Reconnaissance Report",
) -> Path:
    """Save results as a Markdown report."""

    return markdown_output.save(
        results=results,
        filename=filename,
        target=target,
        module=module,
        title=title,
    )


def format_markdown(
    results: Any,
    target: Optional[str] = None,
    module: Optional[str] = None,
    title: str = "AgisRecon2 Reconnaissance Report",
) -> str:
    """Create a Markdown report without saving it."""

    return markdown_output.format_results(
        results=results,
        target=target,
        module=module,
        title=title,
    )